Add generic search endpoint for txns
BlazeWasHere/SYN-Explorer-API pull request #1
Opened 2022-04-04 21:17 UTC by metagabbar

2022-04-05 19:54 UTC, BlazeWasHere requested changes

2022-04-05 19:54 UTC, BlazeWasHere commented on explorer/utils/database.py
> +                sql += f"chain_id_to={to_tx_hash})"
`chain_id_to` is not the same as `to_tx_hash`

2022-04-05 19:54 UTC, BlazeWasHere commented on explorer/utils/database.py
> +                sql += f"from_tx_hash={from_tx_hash})"
sanitize this

2022-04-05 19:54 UTC, BlazeWasHere commented on explorer/utils/database.py
> +                sql += f"chain_id_to={chain_id_to})"
sanitize user input

2022-04-05 19:54 UTC, BlazeWasHere commented on explorer/utils/database.py
> +                sql += f"chain_id_from={chain_id_from}"
please sanitize - prone to sql injection, refer to https://www.psycopg.org/psycopg3/docs/basic/params.html

2022-04-05 19:54 UTC, BlazeWasHere commented on explorer/utils/database.py
> +            if keccak_hash := args["keccak_hash"]:
keep naming consistent, `keccak_hash` should be `kappa`

2022-04-05 19:54 UTC, BlazeWasHere commented on explorer/utils/database.py
> +        sql += f"OFFSET {offset} "
prone to injection too

2022-04-05 19:54 UTC, BlazeWasHere commented on explorer/routes/api/v1/transactions.py
> +    limit = request.args.get('limit', 50, int)
prone to DoS, as there is no limit for `limit` i.e user can set `limit` to 99999999

2022-04-05 19:54 UTC, BlazeWasHere commented on explorer/routes/api/v1/transactions.py
> +    to_tx_hash: Optional[str] = request.args.get('to_tx_hash', None, str)
hashes are of type `HexBytes` not `str`

2022-04-05 21:33 UTC, BlazeWasHere requested changes

2022-04-05 21:33 UTC, BlazeWasHere commented on explorer/utils/database.py
> +            _sql += f"{_param}=%s"
injectable...

2022-04-05 21:33 UTC, BlazeWasHere commented on explorer/utils/database.py
> +        sql += f"DESC LIMIT %s "
slight nuance, unnecessary f-string

2022-04-05 21:33 UTC, BlazeWasHere commented on explorer/routes/api/v1/transactions.py
> +            "keccak_hash": keccak_hash
keep naming consistent, `keccack_hash` should be `kappa`

2022-04-07 18:58 UTC, metagabbar commented on explorer/utils/database.py
> +            _sql += f"{_param}=%s"
All the examples i found online to prevent injection, where inserting directly with a cursor, e.i `c.execute("SELECT * FROM TABLE WHERE NAME=%s", (name))`

Not sure what I'm missing, but doesn't line 300 address this concern ? https://github.com/BlazeWasHere/SYN-Explorer-API/pull/1/files#diff-12a242bcfc7c38ec902a532d18b2f8b505ae786401a94072bbdbd60e012ac7a5R300

2022-04-07 20:54 UTC, metagabbar commented on explorer/utils/database.py
> +            _sql += f"{_param}=%s"
Should I be wrapping it around  `pyscopg2.sql.Identifer`  as such possibly ? https://www.psycopg.org/docs/sql.html

2022-04-08 18:18 UTC, closed without merging

2022-04-08 18:18 UTC, metagabbar commented
Closed owing to rewrite API being higher priority